# Generated by Django 4.2.4 on 2023-09-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.CASCADE, to='appBlog.author'),
            preserve_default=False,
        ),
    ]
